#!/bin/sh /etc/rc.common
START=90
STOP=10
USE_PROCD=1
PROG=/usr/bin/websocket-at-gateway
ARGS=""
start_service() {
    procd_open_instance
    procd_set_param command "$PROG" $ARGS
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
stop_service() {
    procd_kill
}
reload_service() {
    stop
    start
}
service_triggers() {
    procd_add_reload_trigger "websocket-at-gateway"
}